### ISSUE TITLE
College Football listings are duplicated

### ISSUE THREAD

**Issue by andyg5000** [FairfieldTekLLC/HdHomeRunEpgXml#2]
For me, all of the College Football listings are being imported as the same event. They must be using the same identifier in the XML because if I set one to record, they all are set to record.

I've confirmed that HDHomeRun listing has the correct information.
![plex_and_hdhomerun](https://user-images.githubusercontent.com/1800052/44854955-f21d8600-ac37-11e8-84bd-ac5c9754b1e1.png)

**Comment by Winterleaf** [comment]
I have an idea why it's doing it, are you using the windows or python script?

**Comment by Winterleaf** [comment]
This is fixed, just tested it

**Comment by andyg5000** [comment]
Thanks Vincent!
